// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// inv_stereo_cpp
arma::mat inv_stereo_cpp(const arma::mat& u);
RcppExport SEXP _sphericalSIM_inv_stereo_cpp(SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(inv_stereo_cpp(u));
    return rcpp_result_gen;
END_RCPP
}
// jacobian_inv_stereo_cpp
arma::mat jacobian_inv_stereo_cpp(const arma::vec& u);
RcppExport SEXP _sphericalSIM_jacobian_inv_stereo_cpp(SEXP uSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type u(uSEXP);
    rcpp_result_gen = Rcpp::wrap(jacobian_inv_stereo_cpp(u));
    return rcpp_result_gen;
END_RCPP
}
// prox_group_lasso_cpp
arma::vec prox_group_lasso_cpp(const arma::vec& beta, const List& group_idx, const arma::vec& weights, double lambda, double step);
RcppExport SEXP _sphericalSIM_prox_group_lasso_cpp(SEXP betaSEXP, SEXP group_idxSEXP, SEXP weightsSEXP, SEXP lambdaSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_group_lasso_cpp(beta, group_idx, weights, lambda, step));
    return rcpp_result_gen;
END_RCPP
}
// compute_group_penalty_cpp
double compute_group_penalty_cpp(const arma::vec& beta, const List& group_idx, const arma::vec& weights, double lambda);
RcppExport SEXP _sphericalSIM_compute_group_penalty_cpp(SEXP betaSEXP, SEXP group_idxSEXP, SEXP weightsSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_group_penalty_cpp(beta, group_idx, weights, lambda));
    return rcpp_result_gen;
END_RCPP
}
// grad_beta_cpp
arma::vec grad_beta_cpp(const arma::vec& beta, const arma::mat& Theta, const arma::mat& X, const arma::mat& Y, const arma::mat& B, const arma::mat& B_deriv);
RcppExport SEXP _sphericalSIM_grad_beta_cpp(SEXP betaSEXP, SEXP ThetaSEXP, SEXP XSEXP, SEXP YSEXP, SEXP BSEXP, SEXP B_derivSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B_deriv(B_derivSEXP);
    rcpp_result_gen = Rcpp::wrap(grad_beta_cpp(beta, Theta, X, Y, B, B_deriv));
    return rcpp_result_gen;
END_RCPP
}
// compute_objective_cpp
double compute_objective_cpp(const arma::vec& beta, const arma::mat& Theta, const arma::mat& X, const arma::mat& Y, const arma::mat& B, const arma::mat& Omega, double lambda, double gamma, const List& group_idx, const arma::vec& weights);
RcppExport SEXP _sphericalSIM_compute_objective_cpp(SEXP betaSEXP, SEXP ThetaSEXP, SEXP XSEXP, SEXP YSEXP, SEXP BSEXP, SEXP OmegaSEXP, SEXP lambdaSEXP, SEXP gammaSEXP, SEXP group_idxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_objective_cpp(beta, Theta, X, Y, B, Omega, lambda, gamma, group_idx, weights));
    return rcpp_result_gen;
END_RCPP
}
// compute_group_norms_cpp
List compute_group_norms_cpp(const arma::vec& beta, const List& group_idx);
RcppExport SEXP _sphericalSIM_compute_group_norms_cpp(SEXP betaSEXP, SEXP group_idxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_group_norms_cpp(beta, group_idx));
    return rcpp_result_gen;
END_RCPP
}
// compute_prediction_cpp
arma::mat compute_prediction_cpp(const arma::mat& B_new, const arma::mat& Theta);
RcppExport SEXP _sphericalSIM_compute_prediction_cpp(SEXP B_newSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type B_new(B_newSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_prediction_cpp(B_new, Theta));
    return rcpp_result_gen;
END_RCPP
}
// fast_matvec
arma::vec fast_matvec(const arma::mat& A, const arma::vec& x);
RcppExport SEXP _sphericalSIM_fast_matvec(SEXP ASEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_matvec(A, x));
    return rcpp_result_gen;
END_RCPP
}
// compute_objectives_lambda_path
arma::vec compute_objectives_lambda_path(const arma::mat& X, const arma::mat& Y, const arma::mat& beta_mat, const arma::cube& Theta_cube, const arma::cube& B_array, const arma::mat& Omega, const arma::vec& lambdas, double gamma, const List& group_idx, const arma::vec& weights);
RcppExport SEXP _sphericalSIM_compute_objectives_lambda_path(SEXP XSEXP, SEXP YSEXP, SEXP beta_matSEXP, SEXP Theta_cubeSEXP, SEXP B_arraySEXP, SEXP OmegaSEXP, SEXP lambdasSEXP, SEXP gammaSEXP, SEXP group_idxSEXP, SEXP weightsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type beta_mat(beta_matSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type Theta_cube(Theta_cubeSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type B_array(B_arraySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambdas(lambdasSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_objectives_lambda_path(X, Y, beta_mat, Theta_cube, B_array, Omega, lambdas, gamma, group_idx, weights));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_prox_cpp
arma::vec adaptive_prox_cpp(const arma::vec& beta, const List& group_idx, const arma::vec& adaptive_weights, double lambda, double step);
RcppExport SEXP _sphericalSIM_adaptive_prox_cpp(SEXP betaSEXP, SEXP group_idxSEXP, SEXP adaptive_weightsSEXP, SEXP lambdaSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type adaptive_weights(adaptive_weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_prox_cpp(beta, group_idx, adaptive_weights, lambda, step));
    return rcpp_result_gen;
END_RCPP
}
// compute_adaptive_weights_from_beta
arma::vec compute_adaptive_weights_from_beta(const arma::vec& beta_init, const List& group_idx, double gamma_power, double epsilon);
RcppExport SEXP _sphericalSIM_compute_adaptive_weights_from_beta(SEXP beta_initSEXP, SEXP group_idxSEXP, SEXP gamma_powerSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_power(gamma_powerSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_adaptive_weights_from_beta(beta_init, group_idx, gamma_power, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// compute_rss_cpp
double compute_rss_cpp(const arma::mat& Y_pred, const arma::mat& Y_true);
RcppExport SEXP _sphericalSIM_compute_rss_cpp(SEXP Y_predSEXP, SEXP Y_trueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_pred(Y_predSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_true(Y_trueSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_rss_cpp(Y_pred, Y_true));
    return rcpp_result_gen;
END_RCPP
}
// batch_predict_cpp
arma::mat batch_predict_cpp(const arma::mat& X, const arma::vec& beta, const arma::mat& B, const arma::mat& Theta);
RcppExport SEXP _sphericalSIM_batch_predict_cpp(SEXP XSEXP, SEXP betaSEXP, SEXP BSEXP, SEXP ThetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_predict_cpp(X, beta, B, Theta));
    return rcpp_result_gen;
END_RCPP
}
// compute_cv_errors_cpp
arma::vec compute_cv_errors_cpp(const arma::mat& X_test, const arma::mat& Y_test, const List& beta_list, const List& Theta_list, const List& B_list);
RcppExport SEXP _sphericalSIM_compute_cv_errors_cpp(SEXP X_testSEXP, SEXP Y_testSEXP, SEXP beta_listSEXP, SEXP Theta_listSEXP, SEXP B_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_test(X_testSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y_test(Y_testSEXP);
    Rcpp::traits::input_parameter< const List& >::type beta_list(beta_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type Theta_list(Theta_listSEXP);
    Rcpp::traits::input_parameter< const List& >::type B_list(B_listSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_cv_errors_cpp(X_test, Y_test, beta_list, Theta_list, B_list));
    return rcpp_result_gen;
END_RCPP
}
// proximal_gradient_step
List proximal_gradient_step(const arma::vec& beta_current, const arma::mat& Theta, const arma::mat& X, const arma::mat& Y, const arma::mat& B, const arma::mat& B_deriv, const List& group_idx, const arma::vec& weights, double lambda, double step_size, int max_backtrack);
RcppExport SEXP _sphericalSIM_proximal_gradient_step(SEXP beta_currentSEXP, SEXP ThetaSEXP, SEXP XSEXP, SEXP YSEXP, SEXP BSEXP, SEXP B_derivSEXP, SEXP group_idxSEXP, SEXP weightsSEXP, SEXP lambdaSEXP, SEXP step_sizeSEXP, SEXP max_backtrackSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_current(beta_currentSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Theta(ThetaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B_deriv(B_derivSEXP);
    Rcpp::traits::input_parameter< const List& >::type group_idx(group_idxSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< int >::type max_backtrack(max_backtrackSEXP);
    rcpp_result_gen = Rcpp::wrap(proximal_gradient_step(beta_current, Theta, X, Y, B, B_deriv, group_idx, weights, lambda, step_size, max_backtrack));
    return rcpp_result_gen;
END_RCPP
}
